"""empty message

Revision ID: ee94b296deb6
Revises: 
Create Date: 2019-12-17 02:50:06.812205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee94b296deb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tsht_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('act_code_enable', sa.Boolean(), nullable=True),
    sa.Column('act_title', sa.String(length=50), nullable=True),
    sa.Column('wla_hrs_enable', sa.Boolean(), nullable=True),
    sa.Column('wla_code_enable', sa.Boolean(), nullable=True),
    sa.Column('wla_title', sa.String(length=50), nullable=True),
    sa.Column('wlb_hrs_enable', sa.Boolean(), nullable=True),
    sa.Column('wlb_code_enable', sa.Boolean(), nullable=True),
    sa.Column('wlb_title', sa.String(length=50), nullable=True),
    sa.Column('lv_hrs_enable', sa.Boolean(), nullable=True),
    sa.Column('lv_code_enable', sa.Boolean(), nullable=True),
    sa.Column('lv_title', sa.String(length=50), nullable=True),
    sa.Column('tra_hrs_enable', sa.Boolean(), nullable=True),
    sa.Column('tra_code_enable', sa.Boolean(), nullable=True),
    sa.Column('tra_title', sa.String(length=50), nullable=True),
    sa.Column('trb_hrs_enable', sa.Boolean(), nullable=True),
    sa.Column('trb_code_enable', sa.Boolean(), nullable=True),
    sa.Column('trb_title', sa.String(length=50), nullable=True),
    sa.Column('ot_hrs_enable', sa.Boolean(), nullable=True),
    sa.Column('ot_code_enable', sa.Boolean(), nullable=True),
    sa.Column('ot_title', sa.String(length=50), nullable=True),
    sa.Column('remarks_enable', sa.Boolean(), nullable=True),
    sa.Column('remarks_title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('employee_no', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_employee_no'), 'user', ['employee_no'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('tsht', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tsht'], ['tsht_setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate_basis', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    op.drop_table('project')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_employee_no'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tsht_setting')
    op.drop_table('item')
    # ### end Alembic commands ###
